### ISSUE TITLE
Rename helpers of 'plot_*()' consistently?

### ISSUE THREAD

**Issue by maurolepore** [RMI-PACTA/r2dii.plot#428]
We are about to export a bunch of closely related functions but
their name gives no sign of their relationship:

* `to_title()` helps `plot_x()`
* `format_label()` helps `plot_y()`
* `format_label_techmix()` helps `plot_y()`
* `spell_out_technology()` helps `plot_z()`

I think users will more easily discover this functions if their
name was of the form 

```
plot_x(convert_label = label_x)
plot_y(convert_label = label_y, convert_label_tech = label_y_tech)
plot_z(convert_label = label_z)
```

Note I also propose changing `convert_tech_label` to `convert_label_tech`. 
While I usually like the first form because it reads more naturally, I think
here the use of a consistent prefix moves the balance towards 
`convert_label_tech`.﻿

**Comment by MonikaFu** [comment]
maybe `format_label()` could be `format_metric()`? And `format_label_techmix()` could be `recode_metric_techmix()` ?
