### ISSUE TITLE
Move prep functions outside of plot functions

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/r2dii.plot#465]
Currently, the `plot_*()` functions do more than they promise as they contain data preparation steps as well which are not explicit in the function name. Following KISS software design principle, the data preparation functions will be taken out of the `plot_*()` functions and placed in a separate user-facing function which they can (but don't have to) use for structuring the data. The `qplot_*()` functions remain unchanged.

Desired workflow for using `plot_*()` functions will be:
```r
prepped_data <- prep_trajectory(raw_data, parameters)

plot <- plot_trajectory(prepped_data)
```
or

```r
custom_prepped_data <- user_defined_data_prep(raw_data)

plot <- plot_trajectory(custom_prepped_data)
```

FYI @AlexAxthelm @maurolepore

**Comment by MonikaFu** [comment]
FYI @jdhoffa this is the issue that would implement the change mentioned in the current deprecation message. We should evaluate whether we want to introduce it and either do it (I'd be happy to) or not do it and remove the message. At the moment the next release tag is going to be `0.4.0` which the message claims to include this change but it won't.

**Comment by jdhoffa** [comment]
I can see how it would be desirable to split out the functionality! 

So if you still want to, and since the message promises to, I think it would be fine to!

Maybe the `qplot_*` functions can do the prep process too? That way they really are "do everything for me" functions, and then this API would be the more custom approach?

**Comment by MonikaFu** [comment]
> Maybe the qplot_* functions can do the prep process too? That way they really are "do everything for me" functions, and then this API would be the more custom approach?

This is exactly what the idea is. 

> The qplot_*() functions remain unchanged.

The above means that `prep_*()` is part of `qplot_*()` (which it is right now). The change to be implemented is to take `prep_*()` out of `plot_*()` making the `plot_*()` more low level and customizeable.

**Comment by jdhoffa** [comment]
ahaha sorry i missed that! 

sweet then yeah i back it for sure :-)

**Comment by MonikaFu** [comment]
cool! Are you the one who is going to implement it? Realistically speaking, I won't have time for this in this or next sprint. You can see my attempt at implementation of this change for `plot_trajectory()` in #475 .

**Comment by jdhoffa** [comment]
Then I guess I am! Lol XD
