### ISSUE TITLE
Tech Mix conversion for Fossil Flue - Idea 

### ISSUE THREAD

**Issue by georgeharris2deg** [RMI-PACTA/r2dii.plot#52]
Making a note of this for discussion more than a concrete action being needed. 
all to be discussed when time permits. 

Currently, within the fossil fuel sector, there are 3 technologies Oil and gas and coal. 

O&G is given the same unit in the Abns ALD (GJ) 
whereas coal is given in tones

saying this out loud makes me thing the conversion might need to come earlier in the process. As the x-axis on the tech Mix is not the unit of output. Rather, it is the exposure to the respective technologies.  
but I may be wrong (regardless this is still relevant for results at the company level whereby the results are unweighted meaning that the tech mix metric is the absolute technology mix of  company and hence units need to be consistent)

So in order to plot the technology mix for the FF sector (at least at the company level) 
We need to add a conversion from tons of coal into GJ 

@jdhoffa

**Comment by jdhoffa** [comment]
@georgeharris2deg says to close this with no action.
