### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/r2dii.plot#549]
Once PR #543 is merged in, there is a change in API that requires updates to the vignettes so that the examples calling `plot_*()` functions call `prep_*()` before.

**Comment by jdhoffa** [comment]
I think I may have already addressed this here:
https://github.com/RMI-PACTA/r2dii.plot/pull/543/files#diff-42185964731de2859d33719f472188238853913e222a6e64bceb6bc7628c9ac9

**Comment by MonikaFu** [comment]
Right. I missed that somehow. Closing this then. Before we release to CRAN we should do a check if everything renders correctly on the website.
