### ISSUE TITLE
Fix `testthat` checks on Windows

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/r2dii.plot#556]
Note: Windows checks seem to be failing due to the breaking change to `r2dii.data` that introduced the new `increasing_or_decreasing` dataset. 

I don't really understand why only the windows checks fail, since in principle the same checks should be applied to R-CMD-check/macos-latest... in any case, I believe it is unrelated to this PR.

_Originally posted by @jdhoffa in https://github.com/RMI-PACTA/r2dii.plot/issues/552#issuecomment-1959139924_

**Comment by AlexAxthelm** [comment]
Example of failing checks:

https://github.com/RMI-PACTA/r2dii.plot/actions/runs/8001784071/job/21853669742?pr=552

**Comment by AlexAxthelm** [comment]
Looks like. I see that you reran the action and it ran clean. https://github.com/RMI-PACTA/r2dii.plot/actions/runs/8001784071/job/21853669742?pr=552#step:5:3293

Closing this, but maybe you want to wrap those tests in a check on r2dii.data version?

**Comment by jdhoffa** [comment]
I'm thinking the bug was because `posit` package manager was down, so it was trying to install from a sub-par repository mirror. Now that it is back up, things work as expected!
